### ISSUE TITLE
New release with Linux build fix commit included

### ISSUE THREAD

**Issue by lclc** [PureSwift/Silica#3]
Hey, I'm new to swift. As far as I can see I can't use the master branch of packages with the package manager (which makes sense). So I get an error because commit https://github.com/PureSwift/Silica/commit/aa4f82a548224018cd9084da4634089dc4354890 is not included.

Can you make a 1.1.2 release of the package and the dependencies?

Thanks!

(Using the latest Swift release on Ubuntu 16.04)

**Comment by colemancda** [comment]
https://github.com/PureSwift/Silica/releases/tag/1.1.2

**Comment by lclc** [comment]
Thanks a lot! Can you do the same for Cairo and this commit? https://github.com/PureSwift/Cairo/commit/c247d0b031c9b7b8b5c411d68acadfb7a086bb22

Seems to be a dependency of a dependency or so.
